import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; d=json.loads((ROOT/'data/financial_data.json').read_text(encoding='utf-8')); (ROOT/'docs').mkdir(exist_ok=True)
payload=json.dumps(d,ensure_ascii=False).replace('</','<\\/')
html="""<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>삼성전자 재무분석 대시보드</title><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><style>
body{font-family:Arial,sans-serif;margin:0;background:#f5f7fb;color:#172033}header{background:#0b1f3a;color:#fff;padding:28px 5%}main{max-width:1400px;margin:auto;padding:24px 5%}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.card,.panel{background:#fff;border-radius:14px;padding:18px;box-shadow:0 2px 10px #0001;margin-bottom:18px}.num{font-size:25px;font-weight:700}.charts{display:grid;grid-template-columns:2fr 1fr;gap:18px}.tablewrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:12px}th,td{padding:8px;border-bottom:1px solid #e6e9ef;text-align:right;white-space:nowrap}th:first-child,td:first-child{text-align:left}th{background:#eef2f7;position:sticky;top:0}button{padding:9px 14px;border:0;border-radius:8px;margin-right:5px;cursor:pointer}@media(max-width:900px){.grid,.charts{grid-template-columns:1fr}}</style></head><body><header><h1>삼성전자 재무분석 Agent</h1><div>DART Open API · 2010년부터 수집 시도 · 매월 1일 자동 업데이트</div></header><main><div class="grid" id="cards"></div><div class="charts"><div class="panel"><h2>매출액·영업이익</h2><canvas id="t"></canvas></div><div class="panel"><h2>수익성·자본효율</h2><canvas id="m"></canvas></div></div><div class="panel"><h2>국내 비교기업</h2><div class="tablewrap"><table id="p"></table></div></div><div class="panel"><h2>재무표</h2><button onclick="show('annual')">Annual</button><button onclick="show('half_year')">Half-year</button><button onclick="show('quarterly')">Quarterly</button><div id="tbl"></div></div></main><script>
const D=PAYLOAD; const F=x=>x==null?'—':Number(x).toLocaleString('ko-KR',{maximumFractionDigits:2}); const P=x=>x==null?'—':(x*100).toFixed(2)+'%'; let a=D.annual||[],l=a[a.length-1]||{};
document.getElementById('cards').innerHTML=[['매출액',F(l.revenue)],['영업이익',F(l.operating_income)],['영업이익률',P(l.operating_margin)],['ROE',P(l.roe)],['ROIC',P(l.roic)],['CFO',F(l.cfo)],['FCF',F(l.fcf)],['순차입금',F(l.net_debt)]].map(function(x){return '<div class="card">'+x[0]+'<div class="num">'+x[1]+'</div></div>'}).join('');
new Chart(document.getElementById('t'),{type:'line',data:{labels:a.map(x=>x.year),datasets:[{label:'매출액',data:a.map(x=>x.revenue)},{label:'영업이익',data:a.map(x=>x.operating_income)}]}});
new Chart(document.getElementById('m'),{type:'line',data:{labels:a.map(x=>x.year),datasets:[{label:'영업이익률',data:a.map(x=>x.operating_margin*100)},{label:'ROE',data:a.map(x=>x.roe*100)},{label:'ROIC',data:a.map(x=>x.roic*100)}]}});
let pc=['company','year','revenue','operating_margin','roe','roa','roic','net_debt','net_debt_ebitda']; document.getElementById('p').innerHTML='<tr>'+pc.map(function(x){return '<th>'+x+'</th>'}).join('')+'</tr>'+D.peers.map(function(r){return '<tr>'+pc.map(function(x){return '<td>'+(['company','year'].includes(x)?(r[x]??'—'):(['operating_margin','roe','roa','roic'].includes(x)?P(r[x]):F(r[x])))+'</td>'}).join('')+'</tr>'}).join('');
function show(k){let cols=['label','revenue','gross_profit','operating_income','net_income','cfo','capex','fcf','net_debt','gross_margin','operating_margin','net_margin','roa','roe','roic','current_ratio','debt_ratio','equity_ratio','interest_coverage','net_debt_ebitda','asset_turnover','sales_growth','cfo_net_income'];let rows=D[k]||[];document.getElementById('tbl').innerHTML='<div class="tablewrap"><table><tr>'+cols.map(function(c){return '<th>'+c+'</th>'}).join('')+'</tr>'+rows.map(function(r){return '<tr>'+cols.map(function(c){return '<td>'+(c==='label'?(r[c]??'—'):(['gross_margin','operating_margin','net_margin','roa','roe','roic','sales_growth'].includes(c)?P(r[c]):F(r[c])))+'</td>'}).join('')+'</tr>'}).join('')+'</table></div>'} show('annual');
</script></body></html>"""
(ROOT/'docs/index.html').write_text(html.replace('PAYLOAD',payload),encoding='utf-8')
